version: '3.4'

services:
  saafrontend:
    image: nitinsaa1999/saafrontend:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
